### ISSUE TITLE
Looking for a Punjabi corpus (Shahmukhi)

### ISSUE THREAD

**Issue by sinaahmadi** [toqeerehsan/Shahmukhi-POS-Tagging#1]
Hi,

I am looking for a Punjabi corpus that uses the Shahmukhi script. You seem to have some datasets in your repository. Would it be fine if I use them? Otherwise, is there any open-source corpus of Punjabi in Shahmukhi?

Thanks.

**Comment by toqeerehsan** [comment]
Hello

Yes. You can use that corpus.

Here is another corpus link which is bigger.

https://github.com/toqeerehsan/Punjabi-Shahmukhi-Named-Entity-Recognition


Toqeer

**Comment by sinaahmadi** [comment]
Amazing. Thank you!

**Comment by toqeerehsan** [comment]
@sinaahmadi 
Dear Sina Ahmadi, If you are using the Shahmukhi corpus, please cite the article: https://doi.org/10.1016/j.jksuci.2022.12.004

**Comment by toqeerehsan** [comment]
@sinaahmadi
We are also working on Shahmukhi and Urdu language. Please let me know if you need any further assistance regarding corpora, embeddings etc. Thanks.
